name: Undeploy Branch

on:
  pull_request:
    types: [closed]

jobs:
  undeploy:

    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/turnilo

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authenticate on GCP
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Undeploy app
        run: |
          gcloud run services delete turnilo-${GITHUB_REF_NAME//[^a-z]/-} \
            --region europe-west1 \
            --quiet

      - name: Delete Docker image
        run: |
          gcloud container images delete "$IMAGE_NAME:$BRANCH" --quiet
